apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  storageClassName: host-path
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /root/data/pv-test
  persistentVolumeReclaimPolicy: Retain
